from main import scrape_event_names
import asyncio
lis = [
#     ("PG", "https://finchat.io/company/NYSE-PG/investor-relations/", 'true'),
#  ("KO", "https://finchat.io/company/NYSE-KO/investor-relations/", "false"),
#  ("PM", "https://finchat.io/company/NYSE-PM/investor-relations/", 'false'),
#  ("PEP", "https://finchat.io/company/NasdaqGS-PEP/investor-relations/", 'false'),
#  ("MO", "https://finchat.io/company/NYSE-MO/investor-relations/", 'false'),
#  ("MDLZ", "https://finchat.io/company/NasdaqGS-MDLZ/investor-relations/", "false"),
#  ("CVS", 'https://finchat.io/company/NYSE-CVS/investor-relations/', 'false'),
#  ("MCK", "https://finchat.io/company/NYSE-MCK/investor-relations/", 'false'),
#  ("CL", "https://finchat.io/company/NYSE-CL/investor-relations/", 'false'),
#  ("COR", "https://finchat.io/company/NYSE-COR/investor-relations/", "false"),
#  ("KMB", "https://finchat.io/company/NYSE-KMB/investor-relations/", "false"),
#     ("MSFT", "https://finchat.io/company/NasdaqGS-MSFT/investor-relations/", 'false'),
#  ("AAPL", "https://finchat.io/company/NasdaqGS-AAPL/investor-relations/", "false"),
#  ("NVDA", "https://finchat.io/company/NasdaqGS-NVDA/investor-relations/322089/", 'false'),
#  ("META", "https://finchat.io/company/NasdaqGS-META/investor-relations/", 'false'),
#  ("GOOGL", "https://finchat.io/company/NasdaqGS-GOOGL/investor-relations/", 'false'),
#  ("CRM", "https://finchat.io/company/NYSE-CRM/investor-relations/", "false"),
#  ("IBM", 'https://finchat.io/company/NYSE-IBM/investor-relations/', 'false'),
#  ("ORCL", "https://finchat.io/company/NYSE-ORCL/investor-relations/", 'false'),
#  ("PLTR", "https://finchat.io/company/NasdaqGS-PLTR/investor-relations/", 'false'),
#  ("NOW", "https://finchat.io/company/NYSE-NOW/investor-relations/", 'false'),
#  ("INTU", "https://finchat.io/company/NasdaqGS-INTU/investor-relations/", "false"),
#  ("ADBE", "https://finchat.io/company/NasdaqGS-ADBE/investor-relations/", "false"),
 
#  ("QCOM", "https://finchat.io/company/NasdaqGS-QCOM/investor-relations/", 'false'),
#  ("TXN", "https://finchat.io/company/NasdaqGS-TXN/investor-relations/", "false"),
#  ("AMD", "https://finchat.io/company/NasdaqGS-AMD/investor-relations/", 'false'),
#  ("AMAT", "https://finchat.io/company/NasdaqGS-AMAT/investor-relations/", 'false'),
#  ("PANW", "https://finchat.io/company/NasdaqGS-PANW/investor-relations/", 'false'),
#  ("ADI", "https://finchat.io/company/NasdaqGS-ADI/investor-relations/", "false"),
#  ("KLAC", 'https://finchat.io/company/NasdaqGS-KLAC/investor-relations/', 'false'),
#  ("INTC", "https://finchat.io/company/NasdaqGS-INTC/investor-relations/", 'false'),
#  ("LRCX", "https://finchat.io/company/NasdaqGS-LRCX/investor-relations/", 'false'),
#  ("CRWD", "https://finchat.io/company/NasdaqGS-CRWD/investor-relations/", "false"),
#  ("MU", "https://finchat.io/company/NasdaqGS-MU/investor-relations/", "false"),
#  ("APH", "https://finchat.io/company/NYSE-APH/investor-relations/", "false"),
#  ('AVGO', "https://finchat.io/company/NasdaqGS-AVGO/investor-relations/", "false"),
 
 
 ("META", "https://finchat.io/company/NasdaqGS-META/investor-relations/", 'false'),
#  ("APPF", "https://finchat.io/company/NasdaqGM-APPF/investor-relations/", 'false'),
#  ("S", "https://finchat.io/company/NYSE-S/investor-relations/", 'false'),
#  ("PATH", "https://finchat.io/company/NYSE-PATH/investor-relations/", "false"),
#  ("GLOB", 'https://finchat.io/company/NYSE-GLOB/investor-relations/', 'false'),
#  ("DLB", "https://finchat.io/company/NYSE-DLB/investor-relations/", 'false'),
#  ("SNDK", "https://finchat.io/company/NasdaqGS-SNDK/investor-relations/", 'false'),
#  ("AVT", "https://finchat.io/company/NasdaqGS-AVT/investor-relations/", "false"),
 ("PEGA", "https://finchat.io/company/NasdaqGS-PEGA/investor-relations/", "false"),
#  ("DXC", "https://finchat.io/company/NYSE-DXC/investor-relations/", "false"),
#  ('IAC', "https://finchat.io/company/NasdaqGS-IAC/investor-relations/", "false"),
#  ('ALGM', "https://finchat.io/company/NasdaqGS-ALGM/investor-relations/", "false"),
#  ('ZI', "https://finchat.io/company/NasdaqGS-ZI/investor-relations/", "false"),
 ]

for i in lis:
    asyncio.run(scrape_event_names(i[0], i[1], i[2]))